colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: m-sons.com
layout_spectrum: 0.5771967831533402
typography_spectrum: 0.8993288513738662
color:
  brandStrength: 0.9436423624865711
  lightness: 0.9690311518497765
  saturation: 0.7741869739256799
  rhythmicContrast: 0.8254082489293069
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
content: []
title: Welcome to Mson's Trading
description: Simple and quality finishing materials
url: 'http://m-sons.com/'
purpose:
  - type: contact
    url: 'tel:0911200139'
    label: Call 0911200139
  - type: contact
    url: 'mailto:info@m-sons.com'
    label: Contact msons
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d42af180-853e-4802-beed-15bf0c4f3a64.jpg
content_rating:
  adult: false
author:
  name: Murad Mohamed
  email: muradmo@gmail.com
